# -*- coding: utf-8 -*-
"""Melih_Duman_midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swY7ncmYgOeeIyWtaSLCPQMnXV4ZE4m6

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is.

In computer science ,coding or mathematics ,algorithm is the  solution way , solution process or a list of rules to follow in order to solve a problem which we use. However this order must be right . For example when we start to paint , firstly we manage the orders like ; What size should the prints be? What texture?  What colors work just right?  How should the boxes be laid out? or if we give simple example while you dressing you have algorithm for that to , shortly every part of your life , we use algorithms and managing with them.

Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]

I think Algorithmic Design is a collaborate of science and art . So this give us many opportunities to make creative arts  .For example in computer science new programs are developed and some of them make arts with themselves . Best example for that is Google’s Deep Dream neural imaging network.
An app called Dreamscope uses computer science and art and give facility to let users upload photos and run them through Deep Dream’s many patterns.However in Brute-Force design we can not use scientific or algorithmic ways to  create art . We just using own generative thinks to create generative arts.

In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice.

This kind of algorithmic computer science is a very helpful to create some generative art . And algorithmic has many kind of features because it is develop with computer science  and technology 
so we can not calculate how many new features has execute in future years . For example TouchDesigner give us opportunity to see different features of technology and use them effectively while create new art , music , images or videos . So algorithm has change art's creativity and give new generative arts with science . Also this kind of developments has occur some questions about it for example ; algorithmic art is a generative or creative art .

Create a python dictionary for your name surname and year of birth.
"""

melih_dict = {'name' : 'Melih' , 'surname' : 'Duman' , 'yearofbirth' : '08/07/1997'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if 'name'[0] == 'a':
  print("my initial is a")
else :
  print("it is not a ")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len('surname')%3 == 0 : 
  print ("it is divisible")
else :
  print ("not divisible")

"""Change your year of birth to 2678."""

melih_dict.update ({'yearofbirth' : '8/7/2678'})

melih_dict ['yearofbirth']

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""